spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school?useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123123

logging:
  level:
    root: warn
    com.mp.example.dao: trace
  pattern:
    console: '%p%m%n'